export default {
  s3Bucket: "http://s3.eu-west-1.amazonaws.com/media.scanlabprojects",
  tags: [
    // "vr",
    // "installation",
    "web",
    // "artwork",
    "live",
    "tv",
    "film",
    "commercial",
    "heritage",
    "science",
  ],

  order: [
    "desert-pulse",
    "rhythms-around-us",
    "pulse-of-the-earth",
    "felixs-room",
    "replica-real-replica",
    "lost-treasures-of-maya",
    // "pistol",
    "eternal-return",
    "buried-in-the-rock",
    "echoes-from-taiwan",
    "adult-children",
    "man-of-the-woods",
    "guardian-limbo",
    //"ancient-invisible-cities",
    //"post-lenticular-landscapes-korea",
    //"italys-invisible-cities",
    //"mail-rail-viewers",
    //"post-lenticular-landscapes",
    "dreamlife-of-driverless-cars",
    // "crime-scene",
    "displaced-witness",
    //"bartlett-transformation",
    //"mary-rose",
    //"pompeii-new-secrets-revealed",
    //"frozen-relic",
    //"climate-impact-tour",
    "museum-made-digital",
    //"romes-invisible-city-vr",
    "horizontal-humans",
    "ibeyi",
    "phantom",
    //"romes-invisible-city",
    "collapse",
    // "savage-beauty",
    // "stephensons-rocket",
    // 'more4',
    // 'dday',
    // 'pennsylvaniacastle',
    // 'shippinggalleries',
    // 'barn2b',
    "noise",
    // 'bartlettdigitalexhibition',
    "forensic-architecture",
    // 'falstonecountryshow',
    // "lord-nelsons-trafalgar-coat",
  ],
};
